package com.digigate.engineeringmanagement.storemanagement.constant;

public enum RemarkType {
    STORE_DEMAND,
    STORE_ISSUE,
    PROCUREMENT_REQUISITION,
    STORE_RETURN,
    STORE_SCRAP,
    STORE_PART_LOAN,
    STORE_DEMAND_APPROVAL_REMARK,
    STORE_ISSUE_APPROVAL_REMARK,
    STORE_SCRAP_APPROVAL_REMARK,
    STORE_REQUISITION_APPROVAL_REMARK,
    STORE_RETURN_APPROVAL_REMARK,
    PROCUREMENT_RFQ_APPROVAL_REMARK,
    LOGISTIC_RFQ_APPROVAL_REMARK,
    CS_INITIAL_APPROVAL_REMARK,
    CS_AUDIT_APPROVAL_REMARK,
    CS_FINAL_APPROVAL_REMARK,
    PROCUREMENT_PO_APPROVAL_REMARK,
    LOGISTIC_PO_APPROVAL_REMARK,
    PI_OWN_DEPARTMENT_APPROVAL_REMARK,
    PI_FINANCE_APPROVAL_REMARK,
    PI_AUDIT_APPROVAL_REMARK,
    VENDOR_OWN_DEPARTMENT_APPROVAL_REMARK,
    VENDOR_QUALITY_APPROVAL_REMARK ,
    CHECKLIST_OWN_DEPARTMENT_APPROVAL_REMARK,
    CHECKLIST_QUALITY_APPROVAL_REMARK

}
